apiVersion: apps/v1
kind: Deployment
metadata:
  name: pdfmagic
  labels:
    app: pdfmagic
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pdfmagic
  template:
    metadata:
      labels:
        app: pdfmagic
    spec:
      containers:
      - name: pdfmagic
        image: paulfrmbt/pdfmagic
        resources:
          requests:
            cpu: 0.1
        ports:
          - containerPort: 8080
